IF OBJECT_ID('SUP_TLEAF_JUNCTION', 'U') IS NOT NULL DROP TABLE SUP_TLEAF_JUNCTION;
IF OBJECT_ID('TEA', 'U') IS NOT NULL DROP TABLE TEA;
IF OBJECT_ID('TEALEAF', 'U') IS NOT NULL DROP TABLE TEALEAF;
IF OBJECT_ID('EXTRA', 'U') IS NOT NULL DROP TABLE EXTRA;
IF OBJECT_ID('SUPPLIER', 'U') IS NOT NULL DROP TABLE SUPPLIER;

CREATE TABLE TEA
	(TEA_ID			int IDENTITY primary key,
	 TEANAME	    VARCHAR(25),
	 QUANTITY 		NUMERIC(3),
	 BASEPRICE		NUMERIC(3),
	 SALES			NUMERIC(2),
	 TOTAL			NUMERIC(3),
	);
	   
CREATE TABLE TEALEAF
	(TL_ID			int IDENTITY primary key,
	 TLNAME			VARCHAR(20),
	 VARIETY		VARCHAR(15),
	 BRAND			VARCHAR(15),
	 ACIDITY		VARCHAR(15),
	 FLAVOUR		VARCHAR(15),
	 REGION			VARCHAR(15),
	);
	
	CREATE TABLE EXTRA
	(EXT_ID			int IDENTITY primary key,
	 ENAME			VARCHAR(20),
	 CATEGORY		VARCHAR(10),
	 ALLERGEN		VARCHAR(10),
	 AVAILABLE		BIT NOT NULL,
	 PRICE			NUMERIC(3),
	);
	 
	 CREATE TABLE SUPPLIER
	(SUP_ID			int IDENTITY primary key,
	 SNAME			VARCHAR(20),
	 STREET			VARCHAR(20),
	 CITY			VARCHAR(15),
	 ORDER_STATUS   VARCHAR(9),
	 ORDERSTOTAL	NUMERIC(2),
	);
			
CREATE TABLE SUP_TLEAF_JUNCTION
	(STL_ID			int IDENTITY primary key,
	 SUP_ID			int references SUPPLIER(SUP_ID),
	 TL_ID			int references TEALEAF(TL_ID),
	);
	
DECLARE @supFirstId int, @supSecondId int, @supThirdId int;
DECLARE @tLeafMochaId int, @tLeafOrganicId int, @tLeafJavaId int, @tLeafFusionId int, @tLeafMachateId int, @tLeafRussianId int
	
INSERT INTO TEA (TEANAME, QUANTITY, BASEPRICE, SALES, TOTAL) VALUES ('BUBBLE TEA',300,350,23,233);
INSERT INTO TEA (TEANAME, QUANTITY, BASEPRICE, SALES, TOTAL) VALUES ('SPICED THAI',150,450,11,126);
INSERT INTO TEA (TEANAME, QUANTITY, BASEPRICE, SALES, TOTAL) VALUES ('HOT FRUIT TEA',250,450,31,245);
INSERT INTO TEA (TEANAME, QUANTITY, BASEPRICE, SALES, TOTAL) VALUES ('ICED TEA',400,590,10,267);
INSERT INTO TEA (TEANAME, QUANTITY, BASEPRICE, SALES, TOTAL) VALUES ('HOT CHAI LATTE',350,660,17,181);
INSERT INTO TEA (TEANAME, QUANTITY, BASEPRICE, SALES, TOTAL) VALUES ('VANILLA TEA',280,440,19,203);
INSERT INTO TEA (TEANAME, QUANTITY, BASEPRICE, SALES, TOTAL) VALUES ('BLACK TEA LEMONADE',500,370,6,152);
INSERT INTO TEA (TEANAME, QUANTITY, BASEPRICE, SALES, TOTAL) VALUES ('PASSION TEA',250,800,3,199);
	
INSERT INTO TEALEAF (TLNAME, VARIETY, BRAND, ACIDITY, FLAVOUR, REGION) VALUES ('MOCHA','BLACK','LOOSE','HIGH',	'NONE','CHINESE');
SET @tLeafMochaId = ( SELECT IDENT_CURRENT ('TEALEAF') AS Current_Identity);
INSERT INTO TEALEAF (TLNAME, VARIETY, BRAND, ACIDITY, FLAVOUR, REGION) VALUES ('ORGANIC TEA','GREEN','ORGANIC','MEDIUM','FRUIT','INDIAN');
SET @tLeafOrganicId = ( SELECT IDENT_CURRENT ('TEALEAF') AS Current_Identity);
INSERT INTO TEALEAF (TLNAME, VARIETY, BRAND, ACIDITY, FLAVOUR, REGION) VALUES ('JAVAPLANET','OOLONG','FAIR TRADE','LOW','ROSE','CHINESE');
SET @tLeafJavaId = ( SELECT IDENT_CURRENT ('TEALEAF') AS Current_Identity);
INSERT INTO TEALEAF (TLNAME, VARIETY, BRAND, ACIDITY, FLAVOUR, REGION) VALUES ('FUSIONTEA','BLACK','LOOSE','MEDIUM','VANILLA','TAIWANESE');
SET @tLeafFusionId = ( SELECT IDENT_CURRENT ('TEALEAF') AS Current_Identity);
INSERT INTO TEALEAF (TLNAME, VARIETY, BRAND, ACIDITY, FLAVOUR, REGION) VALUES ('MACHATE','WHITE','ORGANIC','LOW','SPICED','ENGLISH');
SET @tLeafMachateId = ( SELECT IDENT_CURRENT ('TEALEAF') AS Current_Identity);
INSERT INTO TEALEAF (TLNAME, VARIETY, BRAND, ACIDITY, FLAVOUR, REGION) VALUES ('RUSSIANLOVE','DARK','LOOSE','LOW','LEMON','RUSSIAN');
SET @tLeafRussianId = ( SELECT IDENT_CURRENT ('TEALEAF') AS Current_Identity);
	
INSERT INTO EXTRA (ENAME, CATEGORY, ALLERGEN, AVAILABLE, PRICE) VALUES ('ALMONDMILK','MILKTYPE','ALMOND',0,100);
INSERT INTO EXTRA (ENAME, CATEGORY, ALLERGEN, AVAILABLE, PRICE)	VALUES ('LACTOSEFREE','MILKTYPE','LACTOSE',1,100);
INSERT INTO EXTRA (ENAME, CATEGORY, ALLERGEN, AVAILABLE, PRICE)	VALUES ('STEVIA','SWEETENER','NONE',1,120);
INSERT INTO EXTRA (ENAME, CATEGORY, ALLERGEN, AVAILABLE, PRICE)	VALUES ('BROWNSUGAR','SWEETENER','NONE',1,50);
INSERT INTO EXTRA (ENAME, CATEGORY, ALLERGEN, AVAILABLE, PRICE)	VALUES ('HONEY','SWEETENER','NONE',1,80);
INSERT INTO EXTRA (ENAME, CATEGORY, ALLERGEN, AVAILABLE, PRICE)	VALUES ('TAKEAWAY','OTHER','NONE',1,160);
	
INSERT INTO SUPPLIER (SNAME, STREET, CITY, ORDER_STATUS, ORDERSTOTAL) VALUES ('ACME, INC.','99 MARKET STREET','GROUNDSVILLE','COMPLETED',12);
SET @supFirstId = ( SELECT IDENT_CURRENT ('SUPPLIER') AS Current_Identity);
INSERT INTO SUPPLIER (SNAME, STREET, CITY, ORDER_STATUS, ORDERSTOTAL) VALUES ('SUPERIOR TEA','1 PARTY PLACE','MENDOCINO','PENDING',26);
SET @supSecondId = ( SELECT IDENT_CURRENT ('SUPPLIER') AS Current_Identity);
INSERT INTO SUPPLIER (SNAME, STREET, CITY, ORDER_STATUS, ORDERSTOTAL) VALUES ('THE HIGH GROUND','100 TEA LANE','MEADOWS','PENDING',17);
SET @supThirdId = ( SELECT IDENT_CURRENT ('SUPPLIER') AS Current_Identity);
	
INSERT INTO SUP_TLEAF_JUNCTION (SUP_ID, TL_ID) VALUES (@supSecondId,@tLeafOrganicId);
INSERT INTO SUP_TLEAF_JUNCTION (SUP_ID, TL_ID) VALUES (@supThirdId,@tLeafFusionId);
INSERT INTO SUP_TLEAF_JUNCTION (SUP_ID, TL_ID) VALUES (@supSecondId,@tLeafMochaId);
INSERT INTO SUP_TLEAF_JUNCTION (SUP_ID, TL_ID) VALUES (@supFirstId,@tLeafMachateId);
INSERT INTO SUP_TLEAF_JUNCTION (SUP_ID, TL_ID) VALUES (@supSecondId,@tLeafJavaId);
INSERT INTO SUP_TLEAF_JUNCTION (SUP_ID, TL_ID) VALUES (@supThirdId,@tLeafRussianId);