//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeaHouse.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXTRA
    {
        public int EXT_ID { get; set; }
        public string ENAME { get; set; }
        public string CATEGORY { get; set; }
        public string ALLERGEN { get; set; }
        public bool AVAILABLE { get; set; }
        public Nullable<decimal> PRICE { get; set; }
    }
}
