//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeaHouse.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPPLIER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUPPLIER()
        {
            this.SUP_TLEAF_JUNCTION = new HashSet<SUP_TLEAF_JUNCTION>();
        }
    
        public int SUP_ID { get; set; }
        public string SNAME { get; set; }
        public string STREET { get; set; }
        public string CITY { get; set; }
        public string ORDER_STATUS { get; set; }
        public Nullable<decimal> ORDERSTOTAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUP_TLEAF_JUNCTION> SUP_TLEAF_JUNCTION { get; set; }
    }
}
