//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeaHouse.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEA
    {
        public int TEA_ID { get; set; }
        public string TEANAME { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
        public Nullable<decimal> BASEPRICE { get; set; }
        public Nullable<decimal> SALES { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
    }
}
