//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeaHouse.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TeaHouseDatabaseEntities : DbContext
    {
        public TeaHouseDatabaseEntities()
            : base("name=TeaHouseDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EXTRA> EXTRA { get; set; }
        public virtual DbSet<SUP_TLEAF_JUNCTION> SUP_TLEAF_JUNCTION { get; set; }
        public virtual DbSet<SUPPLIER> SUPPLIER { get; set; }
        public virtual DbSet<TEA> TEA { get; set; }
        public virtual DbSet<TEALEAF> TEALEAF { get; set; }
    }
}
