//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeaHouse.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEALEAF
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEALEAF()
        {
            this.SUP_TLEAF_JUNCTION = new HashSet<SUP_TLEAF_JUNCTION>();
        }
    
        public int TL_ID { get; set; }
        public string TLNAME { get; set; }
        public string VARIETY { get; set; }
        public string BRAND { get; set; }
        public string ACIDITY { get; set; }
        public string FLAVOUR { get; set; }
        public string REGION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUP_TLEAF_JUNCTION> SUP_TLEAF_JUNCTION { get; set; }
    }
}
